name: CI
on: [push]
jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         - uses: actions/checkout@v2
         - uses: oven-sh/setup-bun@v2
           with:
              bun-version: "latest"

         - run: bun install
         - run: bun test
         - name: Publish with Bun
           env:
              NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: bun publish --access restricted --registry https://npm.pkg.github.com
