name: CI
on: [push]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: oven-sh/setup-bun@v2
           with:
              bun-version: "latest"

         - name: Extract branch name
           shell: bash
           run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
           id: extract_branch

         - run: bun install
         - run: bun test
         - name: Publish with Bun
           env:
              BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
              NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: bun publish --tag $BRANCH_NAME
